import "./globals.css";
import NextAuthSessionProvider from "@/Providers/nextAuthProviders";
import ClientNavbar from "@/components/ClientNavbar";
import ClientFooter from "@/components/ClientFooter";
import { AppProvider } from "@/Providers/AppProviders";

export const metadata = {
  title: "JobHive Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <NextAuthSessionProvider>
        <AppProvider>
          <body>
            <ClientNavbar />
            <section className="min-h-[550px]">{children}</section>
            <ClientFooter />
          </body>
        </AppProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
